application: ciro-s-costa
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
-   url: /stylesheets
    static_dir: guestbook/static/stylesheets

-   url: /guestbook
    script: main.application


libraries:
-   name: webapp2
    version: latest
-   name: django
    version: latest